name: "Test and release"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        id: setup_go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
          check-latest: true

      - name: Tests
        id: test
        run: |
          go mod tidy
          go test -v ./...

  build:
    name: Build
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get all tags
        run: git fetch --force --tags

      - name: Set up Go
        id: setup_go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
          check-latest: true

      - name: Run GoReleaser snapshot
        id: goreleaser-snapshot
        uses: goreleaser/goreleaser-action@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/v*') }}
        with:
          version: latest
          # args: --skip-publish --skip-validate --rm-dist
          args: --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser release
        id: goreleaser-release
        uses: goreleaser/goreleaser-action@v4
        if: ${{ startsWith(github.ref, 'refs/tags/v*') && github.branch == 'main' }}
        with:
          project_name: ${{ github.repository }}
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: ${{ steps.goreleaser-release.outcome == 'success' || steps.goreleaser-snapshot.outcome == 'success' }}
        with:
          name: packages
          path: |
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.zip
            dist/Checksums.txt
          if-no-files-found: error

  upload-to-repository:
    name: Upload to repository
    needs: [ build ]
    #if: ${{ startsWith(github.ref, 'refs/tags/v*') && github.branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: packages

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.REPOSITORY_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Upload using rsync over SSH
        run: |
          packages=$(find packages -type f \( -name "*.rpm" -o -name "*.deb" \))
          
          for package in $packages; do
            package_name=$(basename $package)
            echo "$package_name"
            package_type=${package_name##*.}
            echo "$package_type"
            package_arch=${package_name%.$package_type}
            package_arch=${package_arch##*.}
          
            # Create directory if not exists
            ssh -p ${{ secrets.REPOSITORY_HOST_PORT }} ${{ secrets.REPOSITORY_USER }}@${{ secrets.REPOSITORY_HOST }} \
            "mkdir -p ${{ secrets.REPOSITORY_PATH }}/$package_type/$package_arch"
        
            # Upload package
            rsync -avz --no-perms --no-owner --no-group -e "ssh -p ${{ secrets.REPOSITORY_HOST_PORT }}" $package \
            ${{ secrets.REPOSITORY_USER }}@${{ secrets.REPOSITORY_HOST }}:${{ secrets.REPOSITORY_PATH }}/$package_type/$package_arch/
          done

      - name: Update RPM repositories
        run: |
          packages=$(find packages -type f -name "*.rpm")
  
          for package in $packages; do
            package_name=$(basename $package)
            echo "$package_name"
            package_type=${package_name##*.}
            echo "$package_type"
            package_arch=${package_name%.$package_type}
            package_arch=${package_arch##*.}
        
            # Update rpm repository
            ssh -p ${{ secrets.REPOSITORY_HOST_PORT }} ${{ secrets.REPOSITORY_USER }}@${{ secrets.REPOSITORY_HOST }} \
            "createrepo --update ${{ secrets.REPOSITORY_PATH }}/$package_type/$package_arch"
          done

      - name: Update DEB repository
        run: |
          ssh -p ${{ secrets.REPOSITORY_HOST_PORT }} ${{ secrets.REPOSITORY_USER }}@${{ secrets.REPOSITORY_HOST }} \
            ""
